title: Speech Inpainting based on Multi-layer LSTM Networks
description: Institute for Digital Technologies, Loughborough University London, Haohan Shi, Xiyu Shi, Safak Dogan
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

```yml
  github:
  zip_url: https://fanyi.baidu.com/
  another_url: another value
```